### ISSUE TITLE
[1.5.2] The bullet time effect of Einhander's phase system disappears after any non-flagship cataphract is destroyed.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#19] opened 2021-09-05 13:24 UTC
The effect is gone for the rest of the battle.

Video for demonstration below:
https://youtu.be/6KbGNq2x6LU

**Comment by gomarz** [comment] 2021-09-06 01:18
Wasn't able to reproduce in-dev, though the current version has Einhander using traditional Phase Cloak, so its current system may be the issue.

**Comment by CloudOfNeutronFlux** [comment] 2021-09-14 20:16
Noticed this issue happening to other ships with bullet time effects (phase cloak, temporal shell, etc.) as well. I'll try getting more details on this in a few days.

**Comment by gomarz** [comment] 2021-11-15 16:28
closing for now since it doesn't seem to be isolated to armaa

**Closed by gomarz** 2021-11-15 16:28 UTC
