### ISSUE TITLE
[1.5.2e] Einhander's Pila drones' weapon weirdness.

### ISSUE THREAD

**Issue by CloudOfNeutronFlux** [gomarz/SS-armaa#24] opened 2021-11-08 13:52 UTC
Seems like the weapon replacer script for Pilas only works if the player is controlling the ship at the beginning of the battle. If an Einhander enters the battle under AI control, its Pila drones' weapons will be synced to:
- the Einhander currently controlled by the player
- the Einhander that was most recently controlled by the player
If the player never controlled an Einhander during the session, all AI Einhanders will have Pilas spawning with taclasers.

Haven't tested this with enemy Einhanders, but I can safely assume it's the same for them, too.

This works **across saves, different campaigns and even non-campaign missions** but not different game sessions (restarting the game resets everything to the taclaser).

Videos with captured behavior below:
https://youtu.be/p3fh8kmOL0Y
https://youtu.be/DCqvFjC8CiU

**Comment by gomarz** [comment] 2021-11-15 17:23
Seems to be caused by the einhanders dummy module not spawning in certain conditions. fixed by adding the dummy weapon slot to einhander itself. downside is that removing the module will probably break saves

**Closed by gomarz** 2021-11-15 17:23 UTC
